version: "3.8"
services:
  swagger:
    container_name: swagger-spring-example
    build: .
    ports:
        - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: