version: "3.8"
services:
  swagger:
    container_name: swagger-spring-example
    build: .
    ports:
        - 8080:8080
    network_mode: host

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: