version: "3.3"
services:
  swagger:
    container_name: swagger-spring-example
    build: .
    ports:
        - 8080:8080
    depends_on: 
        - mongodb

  mongodb:
    restart: always
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: